application:
    coinmarketcap:
        api: https://pro-api.coinmarketcap.com/v1 # api coinmarketcap get top coins
        name: coinmarketcap
        secretKeyApi: 8a7e9216-772f-4a5e-81fb-11e37360c519
        counterList: USD, ETH, BTC
        timeframe: 1h

    messari:
        api: https://data.messari.io/api/v1/
        name: messari.io

    topCoinsTotal: 100 # top coins from the topCoinsTotal
    saveRatePeriod: 60 # in minutes
    percentRatePeriod: 120 # in minutes
    minReturnPercent: 10 # in percent
    topCoins: 10
    filterEnabled: true # additional filter
    filterRatePeriod: 360 # in minutes
    coinFilterList: ETH, BTC # list coins filter

    # BigDecimal settings
    roundingMode: HALF_EVEN
    decimals: 2
    extraDecimals: 4
    hundred: 100

    telegram:
      apiToken: "729943301:AAHoKWbkIWqdAyr6kr8dA5Je7Lp6QATmFsk"
      chatId: "124055577"


server:
    port: 8081
